spring.application.name=users

spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb
spring.datasource.username=mouna
spring.datasource.password=mouna


spring.jpa.hibernate.ddl-auto=update

server.port=8081je ne connais